# Generated by Django 3.2.13 on 2023-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_acadeurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadeurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
