# Generated by Django 3.2.13 on 2023-07-09 22:53

from django.db import migrations, models
import urlshortener.apps.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_acadeurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadeurl',
            name='url',
            field=models.CharField(max_length=300, validators=[urlshortener.apps.main.validators.validate_url, urlshortener.apps.main.validators.validate_dot_com]),
        ),
    ]
